const defaultCatalog=[
{cat:"Brigadeiros",name:"Brigadeiros recheados",mode:"cento",price:200,flavors:["Abacaxi com doce de leite","Caipirinha","Chocolate branco com maracujá","Churros","Ferrero","Ninho com Nutella","Paçoquinha com Nutella","Prestígio","Pudim","Romeu e Julieta","Sensação"]},
{cat:"Brigadeiros",name:"Brigadeiros tradicionais",mode:"cento",price:170,flavors:["Ao leite","Abacaxi com coco","Beijinho","Café","Café com leite","Casadinho","Coco queimado","Chocolate branco","Chocolate com laranja","Creme brulee","Laranja","Limão","Maracujá","Meio amargo","Milho verde","Napolitano","Nesquik","Ninho","Paçoquinha"]},
{cat:"Criações",name:"Minhas criações",mode:"cento",price:320,flavors:["Damasco recheado","Figo recheado","Gorgonzola com frutas vermelhas","Gorgonzola com doce de leite","Pistache","Suspiro com morango","Vinho branco com maracujá"]},
{cat:"Bem-casados",name:"Celofane com laço",mode:"unit",price:4.5,flavors:["Doce de leite","Tradicional","Red velvet"]},
{cat:"Bem-casados",name:"Papel italiano com laço",mode:"unit",price:4.7,flavors:["Doce de leite","Tradicional","Red velvet"]},
{cat:"Brownies",name:"Brownie 5x5",mode:"unit",price:4.5,flavors:["Tradicional"]},
{cat:"Brownies",name:"Brownie com doce de leite",mode:"unit",price:5.5,flavors:["Doce de leite"]},
{cat:"Pavlovas",name:"Pavlova mini",mode:"unit",price:3,flavors:["Limão","Vinho branco com damasco e laranja","Frutas vermelhas","Frutas amarelas"]},
{cat:"Bombons",name:"Bombons",mode:"unit",price:3.2,flavors:["Camafeu de nozes","Caribe","Caramelo","Cereja glamour","Coco com amêndoas","Figo com nozes","Nozes com chocolate","Pistache com flor de sal","Surpresa de uva"]},
{cat:"Bombons",name:"Copinho de chocolate",mode:"unit",price:3.5,flavors:["Chocolate","Pistache","Laranja","Limão"]},
{cat:"Suspiros",name:"Suspiros recheados",mode:"unit",price:4,flavors:["Doce de leite","Pistache","Limão","Café","Chocolate","Frutas vermelhas","Baunilha","Brigadeiro branco","Gorgonzola com amora e nozes"]},
{cat:"Suspiros",name:"Pirulito de suspiro",mode:"unit",price:4,flavors:["Leite condensado","Baunilha","Limão","Laranja"]},
{cat:"Suspiros",name:"Saquinho com 10 unidades",mode:"unit",price:4,flavors:["Leite condensado","Baunilha","Limão","Laranja"]},
{cat:"Suspiros",name:"Suspiros - cento",mode:"cento",price:40,flavors:["Leite condensado","Baunilha","Limão","Laranja"]},
{cat:"Torres",name:"Torre de suspiros",mode:"manual",price:0,flavors:["4 andares","5 andares","6 andares","7 andares","8 andares","9 andares","10 andares","11 andares","12 andares"]}
];
let catalog=JSON.parse(localStorage.getItem("nm_visual_catalog")||"null")||JSON.parse(JSON.stringify(defaultCatalog));
let items=[],editingId=null,currentOrderId=null,calDate=new Date(),selectedCalendarDate=new Date().toISOString().slice(0,10);
const R=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const D=d=>d?d.split("-").reverse().join("/"):"-";
const orders=()=>JSON.parse(localStorage.getItem("nm_visual_orders")||"[]");
const setOrders=a=>localStorage.setItem("nm_visual_orders",JSON.stringify(a));
const saveCatalog=()=>localStorage.setItem("nm_visual_catalog",JSON.stringify(catalog));

function openScreen(id){
  document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));
  document.getElementById(id).classList.add("active");
  document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));
  if(id==="home")navHome.classList.add("active");
  if(id==="finance")navFinance.classList.add("active");
  if(id==="orders")navReports.classList.add("active");
  if(id==="more")navMore.classList.add("active");
  if(id==="orders")renderOrders();
  if(id==="contracts")renderContracts();
  if(id==="agenda")renderAgenda();
  if(id==="clients")renderClients();
  if(id==="menu")renderMenu();
  if(id==="finance")renderFinance();
  if(id==="notifications")renderNotifications();
  refreshHome();
  window.scrollTo(0,0);
}

function newOrder(){
  editingId=null;items=[];
  ["clientName","clientPhone","clientCpf","clientAddress","eventType","eventDate","deliveryDate","itemDetails","notes"].forEach(id=>document.getElementById(id).value="");
  deposit.value=0;deliveryTime.value="A combinar";deliveryPlace.value="A definir";renderItems();openScreen("newOrder");
}
function loadCategories(){productCategory.innerHTML=[...new Set(catalog.map(x=>x.cat))].map(c=>`<option>${c}</option>`).join("");loadProducts()}
function loadProducts(){const c=productCategory.value;productSelect.innerHTML=catalog.map((p,i)=>({...p,i})).filter(p=>p.cat===c).map(p=>`<option value="${p.i}">${p.name}</option>`).join("");selectProduct()}
function selectProduct(){const p=catalog[+productSelect.value];basePrice.value=(p?.price||0).toFixed(2);calcType.value="auto";flavorList.innerHTML=(p?.flavors||[]).map(f=>`<label class="flavor"><input class="fcheck" type="checkbox" value="${f}">${f}</label>`).join("");calcPreview()}
function calcData(){const p=catalog[+productSelect.value],q=+productQty.value||0,pr=+basePrice.value||0;let t=calcType.value;if(t==="auto")t=p.mode==="cento"?"fraction":p.mode==="manual"?"manual":"unit";let sub=0,desc="";if(t==="unit"){sub=q*pr;desc=`${q} × ${R(pr)}`}if(t==="fraction"){sub=q/100*pr;desc=`${q} unidades com base em ${R(pr)} o cento`}if(t==="closed"){sub=q*pr;desc=`${q} cento(s) × ${R(pr)}`}if(t==="manual"){sub=pr;desc="Valor manual"}return{p,q,pr,t,sub,desc}}
function calcPreview(){const c=calcData();itemPreview.textContent=R(c.sub);calcDescription.textContent=c.desc}
function addItem(){const c=calcData();if(!c.q){alert("Informe a quantidade.");return}if(c.t==="manual"&&c.pr<=0){alert("Informe o valor.");return}items.push({name:c.p.name,cat:c.p.cat,q:c.q,price:c.pr,type:c.t,sub:c.sub,flavors:[...document.querySelectorAll(".fcheck:checked")].map(x=>x.value),details:itemDetails.value.trim()});itemDetails.value="";renderItems()}
function renderItems(){itemsTable.innerHTML=items.length?items.map((x,i)=>`<tr><td>${x.name}<div class="small">${x.flavors.join(", ")}</div></td><td>${x.q}</td><td>${R(x.sub)}</td><td><button class="btn btn-danger" onclick="items.splice(${i},1);renderItems()">X</button></td></tr>`).join(""):`<tr><td colspan="4">Nenhum item adicionado.</td></tr>`;orderTotal.textContent=R(items.reduce((s,x)=>s+x.sub,0))}
function collectOrder(){return{id:editingId||Date.now(),client:clientName.value.trim(),phone:clientPhone.value.trim(),cpf:clientCpf.value.trim(),address:clientAddress.value.trim(),event:eventType.value.trim(),eventDate:eventDate.value,deliveryDate:deliveryDate.value,items:[...items],total:items.reduce((s,x)=>s+x.sub,0),deposit:+deposit.value||0,payment:payment.value,time:deliveryTime.value,place:deliveryPlace.value,condition:paymentCondition.value,notes:notes.value,status:"Pendente",created:new Date().toISOString()}}
function saveOrder(){const p=collectOrder();if(!p.client||!p.items.length){alert("Informe o cliente e adicione itens.");return}let a=orders(),i=a.findIndex(x=>x.id===p.id);if(i>=0){p.status=a[i].status;a[i]=p}else a.unshift(p);setOrders(a);editingId=p.id;currentOrderId=p.id;refreshHome();alert("Pedido salvo no dispositivo!");showDetails(p.id)}
function editOrder(id){const p=orders().find(x=>x.id===id);if(!p)return;editingId=p.id;clientName.value=p.client||"";clientPhone.value=p.phone||"";clientCpf.value=p.cpf||"";clientAddress.value=p.address||"";eventType.value=p.event||"";eventDate.value=p.eventDate||"";deliveryDate.value=p.deliveryDate||"";deposit.value=p.deposit||0;payment.value=p.payment||"Pix";deliveryTime.value=p.time||"";deliveryPlace.value=p.place||"";paymentCondition.value=p.condition||"";notes.value=p.notes||"";items=p.items||[];renderItems();openScreen("newOrder")}
function editCurrentOrder(){if(currentOrderId)editOrder(currentOrderId)}
function deleteOrder(id){if(!confirm("Excluir este pedido?"))return;setOrders(orders().filter(x=>x.id!==id));renderOrders();refreshHome()}
function renderOrders(){const q=(orderSearch.value||"").toLowerCase();const a=orders().filter(p=>[p.client,p.event,p.status].join(" ").toLowerCase().includes(q));ordersList.innerHTML=a.length?a.map(p=>`<div class="list-card" onclick="showDetails(${p.id})"><div class="list-icon">📅</div><div class="list-body"><div class="list-title">${p.client}</div><div class="list-sub">${p.event||"Evento"} • ${D(p.deliveryDate)} • ${R(p.total)}</div></div><span class="status ${p.status==="Aprovado"?"ok":p.status==="Cancelado"?"cancel":"pending"}">${p.status}</span><div class="arrow">›</div></div>`).join(""):"Nenhum pedido encontrado."}
function renderContracts(){contractsList.innerHTML=orders().map(p=>`<div class="list-card"><div class="list-icon">📄</div><div class="list-body"><div class="list-title">${p.client}</div><div class="list-sub">${D(p.eventDate)} • ${R(p.total)}</div></div><button class="btn btn-outline" onclick="printContract(orders().find(x=>x.id===${p.id}))">Gerar</button></div>`).join("")||"Nenhum pedido salvo."}
function renderClients(){const map={};orders().forEach(p=>{map[p.client]=map[p.client]||{phone:p.phone,count:0,total:0};map[p.client].count++;map[p.client].total+=p.total});clientsList.innerHTML=Object.entries(map).map(([n,v])=>`<div class="list-card"><div class="list-icon">👤</div><div class="list-body"><div class="list-title">${n}</div><div class="list-sub">${v.phone||"-"} • ${v.count} pedido(s) • ${R(v.total)}</div></div></div>`).join("")||"Nenhum cliente cadastrado."}
function showDetails(id){const p=orders().find(x=>x.id===id);if(!p)return;currentOrderId=id;const balance=Math.max(p.total-(p.deposit||0),0),days=Math.ceil((new Date(p.deliveryDate+"T12:00:00")-new Date())/86400000);detailsContent.innerHTML=`<div class="detail-box"><div style="display:flex;justify-content:space-between;gap:10px"><div><h3 style="margin:0">${p.client}</h3><div class="small">📅 ${p.event||"Evento"} &nbsp; 🕒 ${D(p.deliveryDate)} às ${p.time||"-"}</div><div style="color:var(--pink);font-size:12px;margin-top:8px">${days>=0?`Entrega em ${days} dia(s)`: "Entrega vencida"}</div></div><span class="status ${p.status==="Aprovado"?"ok":"pending"}">${p.status}</span></div></div><div class="detail-tabs"><button class="tab active">Resumo</button><button class="tab">Itens</button><button class="tab">Pagamentos</button><button class="tab">Histórico</button></div><div class="detail-box"><div class="detail-row"><span>Total do pedido</span><strong>${R(p.total)}</strong></div><div class="detail-row"><span>Entrada paga</span><strong>${R(p.deposit)}</strong></div><div class="detail-row"><span>Saldo restante</span><strong class="pink">${R(balance)}</strong></div><div class="detail-row"><span>Status</span><strong>${p.status}</strong></div><div class="detail-row"><span>Endereço</span><strong>${p.address||"-"}</strong></div><div class="detail-row"><span>Observações</span><strong>${p.notes||"-"}</strong></div></div><div class="detail-box"><table><thead><tr><th>Item</th><th>Qtd.</th><th>Total</th></tr></thead><tbody>${p.items.map(x=>`<tr><td>${x.name}<div class="small">${x.flavors.join(", ")}</div></td><td>${x.q}</td><td>${R(x.sub)}</td></tr>`).join("")}</tbody></table></div><div class="btn-row"><button class="btn btn-outline" onclick="printContract(orders().find(x=>x.id===${p.id}))">Gerar contrato</button><button class="btn btn-primary" onclick="editOrder(${p.id})">Abrir pedido</button></div>`;openScreen("details")}
function changeStatus(id,status){let a=orders(),p=a.find(x=>x.id===id);if(p){p.status=status;setOrders(a);showDetails(id);refreshHome()}}
function renderAgenda(){calTitle.textContent=calDate.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),days=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];let out=days.map(d=>`<div class="weekday">${d}</div>`).join("");for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;const dayOrders=orders().filter(p=>p.deliveryDate===iso);out+=`<div class="day ${d.getMonth()!==m?"other":""} ${dayOrders.length?"has":""} ${iso===selectedCalendarDate?"selected":""}" onclick="selectCalendarDate('${iso}')">${d.getDate()}${dayOrders.length?'<span class="dot"></span>':''}</div>`}calendar.innerHTML=out;renderSelectedDay()}
function changeMonth(n){calDate=new Date(calDate.getFullYear(),calDate.getMonth()+n,1);renderAgenda()}
function selectCalendarDate(iso){selectedCalendarDate=iso;renderAgenda()}
function renderSelectedDay(){const a=orders().filter(p=>p.deliveryDate===selectedCalendarDate);selectedDayOrders.innerHTML=`<div class="date-group">${new Date(selectedCalendarDate+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}</div>${a.map(p=>`<div class="list-card" onclick="showDetails(${p.id})"><div class="list-icon">📅</div><div class="list-body"><div class="list-title">${p.client}</div><div class="list-sub">${p.event||"Evento"} • ${D(p.deliveryDate)} • ${p.time||"-"}<br>${p.items.reduce((s,x)=>s+x.q,0)} unidades • ${R(p.total)}</div></div><span class="status ${p.status==="Aprovado"?"ok":"pending"}">${p.status}</span></div>`).join("")||'<div class="small">Nenhuma entrega nesta data.</div>'}`}
function renderMenu(){menuList.innerHTML=[...new Set(catalog.map(x=>x.cat))].map(c=>`<div class="date-group">${c}</div>${catalog.map((p,i)=>({...p,i})).filter(p=>p.cat===c).map(p=>`<div class="list-card"><div class="list-icon">🧁</div><div class="list-body"><div class="list-title">${p.name}</div><div class="list-sub">${p.mode==="cento"?R(p.price)+" o cento":p.mode==="manual"?"Valor manual":R(p.price)+" por unidade"}<br>${p.flavors.join(", ")}</div></div><button class="btn btn-outline" onclick="openMenuEditor(${p.i})">Editar</button></div>`).join("")}`).join("")}
function openMenuEditor(i){menuIndex.value=Number.isInteger(i)?i:"";const p=Number.isInteger(i)?catalog[i]:{cat:"",name:"",mode:"unit",price:0,flavors:[]};menuCat.value=p.cat;menuName.value=p.name;menuMode.value=p.mode;menuPrice.value=p.price;menuFlavors.value=p.flavors.join("\n");openModal("menuModal")}
function saveMenuItem(){const p={cat:menuCat.value.trim(),name:menuName.value.trim(),mode:menuMode.value,price:+menuPrice.value||0,flavors:menuFlavors.value.split(/\n|,/).map(x=>x.trim()).filter(Boolean)};if(!p.cat||!p.name){alert("Preencha categoria e nome.");return}if(menuIndex.value==="")catalog.push(p);else catalog[+menuIndex.value]=p;saveCatalog();closeModal("menuModal");renderMenu();loadCategories()}
function resetCatalog(){if(!confirm("Restaurar cardápio original?"))return;catalog=JSON.parse(JSON.stringify(defaultCatalog));saveCatalog();renderMenu();loadCategories()}
function renderFinance(){const a=orders(),total=a.reduce((s,p)=>s+p.total,0),paid=a.reduce((s,p)=>s+(p.deposit||0),0),receive=total-paid;financeContent.innerHTML=`<div class="detail-box"><div class="detail-row"><span>Total orçado</span><strong>${R(total)}</strong></div><div class="detail-row"><span>Entradas recebidas</span><strong>${R(paid)}</strong></div><div class="detail-row"><span>A receber</span><strong class="pink">${R(receive)}</strong></div><div class="detail-row"><span>Pedidos</span><strong>${a.length}</strong></div></div>`}
function pendingOrders(){const today=new Date().toISOString().slice(0,10);return orders().filter(p=>p.status!=="Finalizado"&&p.status!=="Cancelado"&&p.deliveryDate&&p.deliveryDate>today)}
function renderNotifications(){const pending=pendingOrders();notificationList.innerHTML=`<div class="date-group">Hoje • ${new Date().toLocaleDateString("pt-BR")}</div>${pending.map(p=>{const days=Math.ceil((new Date(p.deliveryDate+"T12:00:00")-new Date())/86400000);return `<div class="list-card" onclick="showDetails(${p.id})"><div class="list-icon">📅</div><div class="list-body"><div class="list-title">${p.client}</div><div class="list-sub">${p.event||"Evento"} • ${D(p.deliveryDate)}<br>Entrega em ${days} dia(s)</div></div><div class="arrow">›</div></div>`}).join("")||'<div class="small">Nenhum pedido pendente.</div>'}`;}
function refreshHome(){const a=orders(),today=new Date().toISOString().slice(0,10),pending=pendingOrders(),todayCount=a.filter(p=>p.deliveryDate===today).length,receive=a.reduce((s,p)=>s+Math.max(p.total-(p.deposit||0),0),0);notifBadge.textContent=pending.length;notifBadge.style.display=pending.length?"flex":"none";sumPending.textContent=pending.length;sumToday.textContent=todayCount;sumReceive.textContent=R(receive);maybeNotify(pending)}
async function requestNotifications(){if(!("Notification" in window)){alert("Este navegador não oferece notificações.");return}const p=await Notification.requestPermission();alert(p==="granted"?"Notificações ativadas.":"Permissão não concedida.")}
function maybeNotify(pending){if(!pending.length||!("Notification" in window)||Notification.permission!=="granted")return;const today=new Date().toISOString().slice(0,10),last=localStorage.getItem("nm_last_notification");if(last===today)return;const msg=`Você tem ${pending.length} pedido(s) pendente(s) para entrega.`;navigator.serviceWorker?.ready.then(reg=>reg.showNotification("Noeli Malta Brigadeiros e bem casados",{body:msg,icon:"assets/logo.png",badge:"assets/logo.png",tag:"pedidos-pendentes"}));localStorage.setItem("nm_last_notification",today)}
function exportBackup(){const data={version:1,orders:orders(),catalog,exported:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`backup_noeli_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.orders)||!Array.isArray(d.catalog))throw new Error();setOrders(d.orders);catalog=d.catalog;saveCatalog();refreshHome();alert("Backup restaurado.")}catch(err){alert("Arquivo inválido.")}};r.readAsText(f)}
function printQuote(p){p=p||collectOrder();printArea.innerHTML=`<h2 style="text-align:center">ORÇAMENTO<br>Noeli Malta Brigadeiros e bem casados</h2><p><strong>Cliente:</strong> ${p.client}</p><p><strong>Evento:</strong> ${p.event||"-"} • Entrega: ${D(p.deliveryDate)}</p><table class="ptable"><thead><tr><th>QTD</th><th>DESCRIÇÃO</th><th>TOTAL</th></tr></thead><tbody>${p.items.map(x=>`<tr><td>${x.q}</td><td>${x.name}${x.flavors.length?" - "+x.flavors.join(", "):""}</td><td>${R(x.sub)}</td></tr>`).join("")}</tbody></table><h3 style="text-align:right">Total: ${R(p.total)}</h3>`;window.print()}
function printContract(p){p=p||collectOrder();printArea.innerHTML=`<h2 style="text-align:center">CONTRATO DE PRESTAÇÃO DE SERVIÇOS</h2><p><strong>CONTRATANTE:</strong> ${p.client}, residente em ${p.address||"________"}, CPF nº ${p.cpf||"________"}, telefone ${p.phone||"________"}.</p><p><strong>CONTRATADA:</strong> Noeli Malta Brigadeiros e bem casados, CPF: 820.333.746-53, representada por Noeli Teixeira Malta de Melo, Rua São Paulo, nº 828, Bairro Marília, Lagoa da Prata/MG, CEP 35590-018.</p><table class="ptable"><thead><tr><th>QTD</th><th>DESCRIÇÃO</th><th>VALOR TOTAL</th></tr></thead><tbody>${p.items.map(x=>`<tr><td>${x.q}</td><td>${x.name}${x.flavors.length?" - "+x.flavors.join(", "):""}</td><td>${R(x.sub)}</td></tr>`).join("")}</tbody></table><p><strong>VALOR TOTAL:</strong> ${R(p.total)}</p><p><strong>Data do evento:</strong> ${D(p.eventDate)}<br><strong>Horário:</strong> ${p.time}<br><strong>Local:</strong> ${p.place}<br><strong>Condição:</strong> ${p.condition}</p><p><strong>DADOS PARA PAGAMENTO:</strong><br>Banco 756 – Lagoacred<br>Agência 4113<br>Conta 105996<br>PIX: noelimaltamelo@gmail.com</p><div class="signs"><div class="sign">Noeli Teixeira Malta de Melo</div><div class="sign">${p.client}</div></div>`;window.print()}
function openModal(id){document.getElementById(id).classList.add("open")}function closeModal(id){document.getElementById(id).classList.remove("open")}
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBox.style.display="block"});installBtn.addEventListener("click",async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBox.style.display="none"}});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").then(reg=>reg.update()));
loadCategories();renderItems();refreshHome();
