window.Dev=window.Dev||{};
Object.assign(Dev,{
 STATUS:['Orçamento','Aguardando aprovação','Aprovado','Entrada recebida','Em produção','Pronto','Entregue','Finalizado','Cancelado'],
 normalize:o=>({...o,payments:Array.isArray(o.payments)?o.payments:[],history:Array.isArray(o.history)?o.history:[],contractStatus:o.contractStatus||'Pendente',status:o.status||'Orçamento'}),
 all:()=>orders().map(Dev.normalize),save:a=>setOrders(a.map(Dev.normalize)),
 paid:p=>(p.payments||[]).reduce((s,x)=>s+Number(x.amount||0),0)+(p.payments?.length?0:Number(p.deposit||0)),
 balance:p=>Math.max(Number(p.total||0)-Dev.paid(p),0),
 payState:p=>Dev.balance(p)<=.009?'Pago':Dev.paid(p)>0?'Parcial':'Pendente',
 history:(p,text)=>{p.history=p.history||[];p.history.unshift({date:new Date().toISOString(),text})},
 prod:p=>['Aprovado','Entrada recebida','Em produção','Pronto'].includes(p.status),
 inject(){
  const grid=document.querySelector('#home .tile-grid');
  if(grid&&!document.getElementById('devProductionTile'))grid.insertAdjacentHTML('beforeend',`<button id="devProductionTile" class="tile teal" onclick="openScreen('production')"><div class="tile-icon">🏭</div><div class="tile-title">Produção</div><div class="tile-sub">Ordens e consolidação</div></button><button class="tile rose" onclick="openScreen('payments')"><div class="tile-icon">💳</div><div class="tile-title">Pagamentos</div><div class="tile-sub">Entradas e saldos</div></button>`);
  const summary=document.querySelector('#home .section-card');if(summary&&!document.getElementById('sumProduction'))summary.insertAdjacentHTML('beforeend',`<div class="summary-row" onclick="openScreen('production')"><div class="summary-icon">🏭</div><div class="summary-main"><div class="summary-label">Pedidos para produção</div></div><div id="sumProduction" class="summary-value">0</div><div class="arrow">›</div></div>`);
  const finance=document.getElementById('finance');if(finance&&!document.getElementById('production'))finance.insertAdjacentHTML('beforebegin',`<section id="production" class="screen"><div class="page-header"><button class="back-btn" onclick="openScreen('home')">‹</button><h2>Produção</h2><span></span></div><div class="content"><div class="form-card"><div class="g2"><div><label>Data de produção</label><input id="productionDate" type="date" onchange="renderProduction()"></div><div><label>Visualização</label><select id="productionMode" onchange="renderProduction()"><option value="orders">Por pedido</option><option value="consolidated">Consolidada</option></select></div></div></div><div id="productionContent"></div></div></section><section id="payments" class="screen"><div class="page-header"><button class="back-btn" onclick="openScreen('home')">‹</button><h2>Pagamentos</h2><span></span></div><div class="content"><div id="paymentsContent"></div></div></section>`);
  const block=document.querySelector('#newOrder .form-card:last-of-type');if(block&&!document.getElementById('orderStatus'))block.querySelector('.g2')?.insertAdjacentHTML('afterend',`<div class="g2"><div><label>Status do pedido</label><select id="orderStatus">${Dev.STATUS.map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>Contrato</label><select id="contractStatus"><option>Pendente</option><option>Gerado</option><option>Assinado</option><option>Dispensado</option></select></div></div>`);
  if(!document.getElementById('paymentModal'))document.body.insertAdjacentHTML('beforeend',`<div id="paymentModal" class="modal"><div class="modal-card"><div class="production-header"><h3>Registrar pagamento</h3><button class="btn btn-light" onclick="closeModal('paymentModal')">Fechar</button></div><input type="hidden" id="paymentOrderId"><div class="g2"><div><label>Valor recebido</label><input id="paymentAmount" type="number" step="0.01"></div><div><label>Data</label><input id="paymentDate" type="date"></div></div><div class="g2"><div><label>Forma</label><select id="paymentMethod"><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>Transferência</option><option>Outro</option></select></div><div><label>Descrição</label><input id="paymentNote"></div></div><div class="btn-row"><button class="btn btn-primary" onclick="savePayment()">Salvar pagamento</button></div></div></div>`);
  const v=document.querySelector('#more .small');if(v)v.innerHTML='Brigadeiros e bem casados<br>Versão 2.1.0 — Desenvolvimento';
 },
 ready(){Dev.inject();if(window.productionDate)productionDate.value=new Date().toISOString().slice(0,10);refreshHome()}
});
