(()=>{
const KEY='nm_v3_clients';
const getClients=()=>{let a=[];try{a=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{};const map={};Dev.all().forEach(p=>{const k=(p.phone||p.client||'').trim().toLowerCase();if(!k)return;map[k]={id:k,name:p.client||'',phone:p.phone||'',cpf:p.cpf||'',address:p.address||'',notes:'',source:'pedido',...(map[k]||{})}});a.forEach(c=>map[c.id]=c);return Object.values(map)};
const saveClients=a=>localStorage.setItem(KEY,JSON.stringify(a));
window.V3={getClients,saveClients};
function inject(){
 const home=document.querySelector('#home .content');
 if(home&&!document.getElementById('v3Dashboard'))home.insertAdjacentHTML('afterbegin',`<div id="v3Dashboard" class="v3-dashboard"><div class="v3-kpi"><span>Orçamentos</span><strong id="v3Quotes">0</strong></div><div class="v3-kpi"><span>Pedidos confirmados</span><strong id="v3Confirmed">0</strong></div><div class="v3-kpi"><span>Em produção</span><strong id="v3Production">0</strong></div><div class="v3-kpi"><span>A receber</span><strong id="v3Receive">R$ 0,00</strong></div></div>`);
 const clients=document.getElementById('clients');
 if(clients&&!document.getElementById('newClientBtn'))clients.querySelector('.page-header')?.insertAdjacentHTML('beforeend','<button id="newClientBtn" class="page-action" onclick="openClientModal()">＋</button>');
 const ordersContent=document.querySelector('#orders .content');
 if(ordersContent&&!document.getElementById('orderFilters'))ordersContent.insertAdjacentHTML('afterbegin',`<div id="orderFilters" class="v3-filters"><select id="filterCommercial" onchange="renderOrders()"><option value="">Todos os tipos</option><option>Orçamento</option><option>Confirmado</option><option>Cancelado</option></select><select id="filterPayment" onchange="renderOrders()"><option value="">Todos os pagamentos</option><option>Pendente</option><option>Parcial</option><option>Pago</option></select><input id="filterDate" type="date" onchange="renderOrders()"></div>`);
 if(!document.getElementById('clientModal'))document.body.insertAdjacentHTML('beforeend',`<div id="clientModal" class="modal"><div class="modal-card"><div class="production-header"><h3>Cliente</h3><button class="btn btn-light" onclick="closeModal('clientModal')">Fechar</button></div><input type="hidden" id="clientId"><div class="g2"><div><label>Nome</label><input id="clientFormName"></div><div><label>WhatsApp</label><input id="clientFormPhone"></div></div><div class="g2"><div><label>CPF</label><input id="clientFormCpf"></div><div><label>Endereço</label><input id="clientFormAddress"></div></div><label>Observações</label><textarea id="clientFormNotes"></textarea><div class="btn-row"><button class="btn btn-primary" onclick="saveClient()">Salvar cliente</button></div></div></div>`);
}
window.openClientModal=id=>{const c=id?getClients().find(x=>x.id===id):null;clientId.value=c?.id||'';clientFormName.value=c?.name||'';clientFormPhone.value=c?.phone||'';clientFormCpf.value=c?.cpf||'';clientFormAddress.value=c?.address||'';clientFormNotes.value=c?.notes||'';openModal('clientModal')};
window.saveClient=()=>{const name=clientFormName.value.trim();if(!name){alert('Informe o nome.');return}let a=getClients();const id=clientId.value||((clientFormPhone.value||name).trim().toLowerCase()+'-'+Date.now());const c={id,name,phone:clientFormPhone.value.trim(),cpf:clientFormCpf.value.trim(),address:clientFormAddress.value.trim(),notes:clientFormNotes.value.trim(),source:'cadastro'};const i=a.findIndex(x=>x.id===id);if(i>=0)a[i]=c;else a.push(c);saveClients(a.filter(x=>x.source==='cadastro'));closeModal('clientModal');renderClients()};
window.renderClients=()=>{const a=getClients().sort((x,y)=>x.name.localeCompare(y.name));clientsList.innerHTML=a.length?a.map(c=>{const ps=Dev.all().filter(p=>(p.phone&&c.phone&&p.phone===c.phone)||p.client===c.name);return `<div class="list-card"><div class="list-icon">👤</div><div class="list-body"><div class="list-title">${c.name}</div><div class="list-sub">${c.phone||'-'} • ${ps.length} pedido(s) • ${R(ps.reduce((s,p)=>s+p.total,0))}</div></div><button class="btn btn-outline" onclick="openClientModal('${c.id.replace(/'/g,"\\'")}')">Editar</button></div>`}).join(''):'Nenhum cliente cadastrado.'};
const oldRenderOrders=window.renderOrders;
window.renderOrders=()=>{const q=(orderSearch.value||'').toLowerCase(),fc=window.filterCommercial?.value||'',fp=window.filterPayment?.value||'',fd=window.filterDate?.value||'';const a=Dev.all().filter(p=>{const commercial=p.commercialStatus||Workflow?.commercial(p)||'';return [p.client,p.event,p.status,Dev.payState(p)].join(' ').toLowerCase().includes(q)&&(!fc||commercial===fc)&&(!fp||Dev.payState(p)===fp)&&(!fd||p.deliveryDate===fd)});ordersList.innerHTML=a.length?a.map(p=>`<div class="list-card" onclick="showDetails(${p.id})"><div class="list-icon">📅</div><div class="list-body"><div class="list-title">${p.client}</div><div class="list-sub">${p.event||'Evento'} • ${D(p.deliveryDate)} • ${R(p.total)}<br>${p.commercialStatus||Workflow?.commercial(p)||'Orçamento'} • ${Dev.payState(p)}</div></div><span class="status ${p.status==='Cancelado'?'cancel':p.status==='Finalizado'?'ok':'pending'}">${p.status}</span><div class="arrow">›</div></div>`).join(''):'Nenhum pedido encontrado.'};
const oldRefresh=window.refreshHome;
window.refreshHome=()=>{oldRefresh();const a=Dev.all();if(!document.getElementById('v3Dashboard'))return;v3Quotes.textContent=a.filter(p=>(p.commercialStatus||Workflow?.commercial(p))==='Orçamento').length;v3Confirmed.textContent=a.filter(p=>(p.commercialStatus||Workflow?.commercial(p))==='Confirmado').length;v3Production.textContent=a.filter(p=>(p.operationalStatus||Workflow?.operational(p))==='Em produção').length;v3Receive.textContent=R(a.reduce((s,p)=>s+Dev.balance(p),0))};
const oldReady=Dev.ready;Dev.ready=()=>{oldReady();inject();refreshHome()};
inject();refreshHome();
})();